//==============================================================================
//
// (c) Copyright  1991-1997 Meta Software M.S., S.A
// All rights reserved.
//
// Module:              m4dispatcher
// File:                m4dpchres.hpp   
// Project:             mind4.x      
// Author:              Meta4 Spain, S.A
// Date:                Aug-2000
// Language:            C++
// Operating System:    WINDOWS NT, UNIX
// Design Document:     XXX.DOC
//
//
// Definition:
//
//    This module defines the error codes for the channel
//
//
//==============================================================================


#ifndef __M4DPCHRES_HPP__
#define __M4DPCHRES_HPP__


#include <m4res.hpp>

//----------------------------------------------------------------------------
//                                 DISPATCHER
//----------------------------------------------------------------------------

#define M4_ERR_DPCH_GENERICMSG				0x0010 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOINITIALIZEPARAMETER			0x0011 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOINITIALIZEAGENT			0x0012 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOINITIALIZEAGENTACTION		0x0013 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETHOSTNAME				0x0014 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTARTACCEPTING			0x0015 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_UNKNOWNADMINAGENTACTION		0x0016 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTARTCONFIGPARAM	0x0017 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_INCORRECTADMINAGENTBASEPORT		0x0018 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTARTXMLANSWER		0x0019 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTARTEXECUTEACTION	0x001A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTOPCONFIGPARAM		0x001B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTNODEINFO			0x001C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTUPDATENODEINFO		0x001D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTOPXMLANSWER		0x001E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMINAGENTSTOPEXECUTEACTION	0x001F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_ADMINAGENTINVALIDLOAD			0x0020 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSERVERAGENTNODEINFO			0x0021 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_UNKNOWNCLIENTAGENTACTION		0x0022 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCLIENTAGENTSERVERCANDIDATE	0x0023 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_COMMUNICATIONLAYERPROTOCOLERROR	0x0024 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_COMMUNICATIONLAYERSESSIONIDERROR	0x0025 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CLIENTCONNECTIONBROKEN		0x0026 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCOMMUNICATIONEXECUTEACTION	0x0027 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_COMMUNICATIONXMLPROTOCOLERROR	0x0028 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_COMMUNICATIONXMLSESSIONIDERROR	0x0029 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CLIENTXMLCONNECTIONBROKEN		0x002A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CLIENTXMLCONNECTIONCLOSE		0x002B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCOMMUNICATIONXMLEXECUTEACTION	0x002C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CONNECTIONESTABLISHEDERROR		0x002D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_XMLCONNECTIONESTABLISHEDERROR	0x002E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_SENDINGXMLREPLYERROR			0x002F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_SENDINGREPLYERROR			0x0030 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_REPLYSENDINGERROR			0x0031 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_OPENINGCTRLCONNECTIONERROR		0x0032 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_SENDINGCTRLREPLYERROR			0x0033 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTOPLISTENING				0x0034 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CLOSINGCONNECTIONERROR		0x0035 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOMEMORYALLOCATION			0x0036 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCONSISTENCYEXECUTORASSIGNED	0x0037 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCONFIGQUERYEXECUTORASSIGNED	0x0038 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCONFIGURATIONLIST			0x0039 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMONREQUEST				0x003A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADMONREQUESTREPLY			0x003B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETNEXTNODEINFO			0x003C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLGETHOSTNAME			0x003D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETNEXTNODEINFOFORCLIENT		0x003E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETACKPDUFORCLIENT			0x003F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLREQUEST				0x0040 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOBUILDREQUESTREPLY			0x0041 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLPARSEACTION			0x0042 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCLIENTBUFFER				0x0043 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOREDIRECTCLIENTCONNECT		0x0044 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLAPPCTLPORT				0x0045 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLAPPCTLBUFFER			0x0046 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOXMLAPPCTLHOST				0x0047 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSITENODE				0x0048 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSITENODEID				0x0049 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSITENODEHOST				0x004A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADDSITENODE				0x004B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOFINDSITENODE				0x004C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOREMOVESITENODE			0x004D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOCANDIDATESITENODE			0x004E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETSITENODEINFO			0x004F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTARTADMONREQUEST			0x0050 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTARTADMONREQUESTREPLY		0x0051 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOEXECUTESTARTADMONREQUEST		0x0052 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTOPADMONREQUEST			0x0053 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTOPADMONREQUESTREPLY		0x0054 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOEXCUTESTOPADMONREQUEST		0x0055 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOUPDATESERVERCONFIGNAME		0x0056 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOUPDATESERVERCONFIGSTATUS		0x0057 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOADDDPCHREQUEST			0x0058 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOREMOVEDPCHREQUEST			0x0059 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTACCEPTPDUACTIONEXECUTOR	0x005A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTACCEPTXMLACTIONEXECUTOR	0x005B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTREADPDUACTIONEXECUTOR		0x005C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTREADXMLACTIONEXECUTOR		0x005D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTWRITEPDUACTIONEXECUTOR	0x005E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPOSTWRITEXMLACTIONEXECUTOR	0x005F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSENDPDUACTIONEXECUTOR		0x0060 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOPROCESSPDUACTIONEXECUTOR		0x0061 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSENDXMLACTIONEXECUTOR		0x0062 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTARTCONFIGACTIONEXECUTOR		0x0063 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSTOPCONFIGACTIONEXECUTOR		0x0064 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOINITIALIZEADMINAGENTXMLPARSE	0x0065 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOINITIALIZEDPSAGENTXMLPARSE	0x0066 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOSHUTDOWNDISPATCHER			0x0067 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOAPPCTLINHOST					0x0068 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_NOGETAPPCTLNODEINFO				0x0069 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_ERRORFROMAPPCTL					0x006A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_STARTCONFIG_TIMEOUT				0x006B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_STARTCONFIG_MAXRETRIES			0x006C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_CONFIG_PROPERTY 				0x006D + M4_DPCH_ERROR_BASE

#define M4_ERR_DPCH_REMOVECFGNOPROPERTY	0x006E + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_REMOVECFGNONODE	0x006F + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_REMOVECFGNOEXECUTOR	0x0070 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_REMOVECFGNOREPLYREQUEST	0x0071 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_REMOVECFGNOEXECUTEADMREQ	0x0072 + M4_DPCH_ERROR_BASE
#define M4_INF_DPCH_REMOVECFGSUCCESS	0x0073 + M4_DPCH_ERROR_BASE
#define M4_INF_DPCH_REMOVECFGPROCESSING	0x0074 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_DENIED_ADMIN_HOST	0x0075 + M4_DPCH_ERROR_BASE

#define M4_ERR_DPCH_START_SRV_MONITOR		0x0076 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_END_SRV_MONITOR			0x0077 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_SET_SRV_DISCARDED		0x0078 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_UNSET_SRV_DISCARDED		0x0079 + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_POLLING_LOGIN_FAILED	0x007A + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_OPEN_TRACE_FILE_ERROR	0x007B + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_POLLING_DECRYPT_ERROR	0x007C + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_STORE_MONITOR_ERROR		0x007D + M4_DPCH_ERROR_BASE
#define M4_ERR_DPCH_START_MONITOR_ERROR		0x007E + M4_DPCH_ERROR_BASE


#endif
