#ifndef SUBSYSTEMIDS
#define SUBSYSTEMIDS

#include <ssnames.hpp>

#define MAX_NUM_INSTANCES					50


#define M4_SERVER_SUBSYSTEM					0
#define M4_EXECUTOR_TEST_SUBSYSTEM			1
#define M4_EXECUTOR_CHANNEL_SUBSYSTEM		2
#define M4_EXECUTOR_ECHO_SUBSYSTEM			3
#define M4_EXECUTOR_JOB_SUBSYSTEM			4
#define M4_EXECUTOR_METHOD_SUBSYSTEM		5
#define M4_EXECUTOR_PERSIST_SUBSYSTEM		6
#define M4_EXECUTOR_LOAD_SUBSYSTEM			7
#define M4_EXECUTOR_UUSS_SUBSYSTEM			8
#define M4_EXECUTOR_SESSION_SUBSYSTEM		9
#define M4_EXECUTOR_JOB_GET_SUBSYSTEM		10
#define M4_EXECUTOR_JOB_EXECUTE_SUBSYSTEM	11
#define M4_EXECUTOR_PROXY_SUBSYSTEM			12
#define M4_EXECUTOR_NODB_SUBSYSTEM			13
#define M4_EXECUTOR_MD_SUBSYSTEM			14
#define M4_EXECUTOR_ENV_SUBSYSTEM			15
#define M4_EXECUTOR_JOB_CANCEL_SUBSYSTEM	16
#define M4_EXECUTOR_M4XML					17
#define M4_CONTAINER_SUBSYSTEM				29
#define M4_APPSRV_SUBSYSTEM					30
#define M4_LM_SUBSYSTEM						31
#define M4_RECEIVERLIST_SUBSYSTEM			32
#define M4_RECEIVER_SUBSYSTEM				33
#define M4_SENDERLIST_SUBSYSTEM				34
#define M4_SENDER_SUBSYSTEM					35
#define M4_ACCEPTORLIST_SUBSYSTEM			36
#define M4_ACEPTOR_SUBSYSTEM				37
#define M4_SESSMANAGER_SUBSYSTEM			38
#define M4_SESSMANAGERLIST_SUBSYSTEM		39
#define M4_SCHEDULER_SUBSYSTEM				40
#define M4_SCHEDULERLIST_SUBSYSTEM			41
#define M4_DISTRIBUTORLIST_SUBSYSTEM		42
#define M4_DISTRIBUTOR_SUBSYSTEM			43
#define M4_SERVICELIST_SUBSYSTEM			44
#define M4_SERVICE_SUBSYSTEM				45
#define M4_LDB_SUBSYSTEM					46
#define M4_CACHE_SUBSYSTEM					47
#define M4_ADMIN_ACCEPTORLIST_SUBSYSTEM		48
#define M4_ADMIN_ACCEPTOR_SUBSYSTEM			49
#define M4_LAUNCHERLIST_SUBSYSTEM			50
#define M4_LAUNCHER_SUBSYSTEM				51
#define M4_USERS_SUBSYSTEM					52
#define M4_USER_SUBSYSTEM					53
#define M4_SESSION_SUBSYSTEM				54
#define M4_ROLE_SUBSYSTEM					55
#define M4_OLTP_SUBSYSTEM					56
#define M4_CONVERSATIONAL_SERVICE_SUBSYSTEM	57
#define M4_JOB_SCHEDULER_SUBSYSTEM			58
#define M4_CACHES_SUBSYSTEM					59
#define M4_SESS_CH_SERVICE_SUBSYSTEM		60
#define M4_UUSS_SERVICE_SUBSYSTEM			61
#define M4_ENVIROMENT_SERVICE				62
#define M4_REQUEST_SUBSYSTEM				63
#define M4_PROXY_SUBSYSTEM					64
#define M4_METADATA_SUBSYSTEM				65
#define M4_SUPERVISOR_SUBSYSTEM				66
#define M4_SUPERVISORS_SUBSYSTEM			67
#define M4_SUPERVISOR_COMMANDS				68
#define M4_SERVICE_JOB_EXECUTE				69
#define M4_SERVICE_JOB_CANCEL				70
#define M4_LOAD_ESTIMATOR_SUBSYSTEM			71
#define M4_MEMORY_CONTROL_SUBSYSTEM			72
#define M4_MEMORY_LEVEL_SUBSYSTEM			73
#define M4_PROXY_SPACES_SUBSYSTEM			74
#define M4_PROXY_SPACE_SUBSYSTEM			75
#define M4_XML_SUBSYSTEM					76
#define M4_DMS_SUBSYSTEM					77
#define M4_DMS_MANAGER_SUBSYSTEM			78
#define M4_EXECUTOR_JOB_EXECUTE_SUBSYSTEM28	79
#define M4_ECHO_SERVICE_SUBSYSTEM			80
#define M4_DISPATCHERSS_SUBSYSTEM			81
#define M4_SERVICE_TABLE					82
#define M4_LOAD_ESTIMATION_RULES			83
#define M4_DMSFS_SUBSYSTEM					84
#define M4_TRACE_SUBSYSTEM					85
#define M4_LOG_SUBSYSTEM					86
#define M4_LDBINSPECTOR_SUBSYSTEM			87
//#define M4_BENCHMARK_SUBSYSTEM				88
#define M4_SNMP_SUBSYSTEM					89

#endif

