

#ifndef _M4_ACTION_CONSTANTS
#define _M4_ACTION_CONSTANTS


//ACTION NAMES

const m4pchar_t DISPATCH_REQUEST_ACTION		= "DISPATCH_REQUEST_ACTION" ;
const m4pchar_t	CONTROL_REQUEST_ACTION		= "PROCESS_CONTROL_REQUEST_ACTION" ;
const m4pchar_t SEND_REQUEST_ACTION			= "SEND_REQUEST_ACTION" ;
const m4pchar_t NEW_USER_ACTION				= "NEW_USER_ACTION" ;
const m4pchar_t END_USER_SESSION_ACTION		= "END_USER_SESSION_ACTION" ;
const m4pchar_t REGISTER_REQUEST_ACTION		= "REGISTER_REQUEST_ACTION" ;
const m4pchar_t DEREGISTER_REQUEST_ACTION	= "DEREGISTER_REQUEST_ACTION" ;
const m4pchar_t CANCEL_USER_REQUEST_ACTION 	= "CANCEL_USER_REQUEST_ACTION" ;
const m4pchar_t SEND_BUFFER_AS_CLIENT		= "SEND_BUFFER_AS_CLIENT" ;
const m4pchar_t OPEN_CONNECTION_ACTION		= "OPEN_CONNECTION" ;
const m4pchar_t POST_ACCEPT_PDU_ACCTION		= "POST_ACCEPT_PDU_ACCTION" ;
const m4pchar_t POST_ACCEPT_PDU_ADMIN_ACCTION = "POST_ACCEPT_PDU_ADMIN_ACCTION" ;
const m4pchar_t POST_WRITE_PDU_ACCTION		= "POST_WRITE_PDU_ACCTION" ;
const m4pchar_t POST_READ_PDU_ACCTION		= "POST_READ_PDU_ACCTION" ;
const m4pchar_t POST_WRITE_BUFFER_ACCTION	= "POST_WRITE_BUFFER_ACCTION" ;
const m4pchar_t CLOSE_CONNECTION_ACTION		= "CLOSE_CONNECTION_ACTION" ;
const m4pchar_t RECOVER_SESSION_ACTION		= "RECOVER_SESSION" ;
const m4pchar_t PROCESS_REQUEST_ACTION		= "PROCESS_REQUEST" ;
const m4pchar_t REMOVE_CONNECTION_ACTION	= "REMOVE_CONNECTION_ACTION" ;
const m4pchar_t REPLACE_REQUEST				= "REPLACE_REQUEST_ACTION" ;
const m4pchar_t PROCESS_CLOSSED_CONN_ACTION = "PROCESS_CLOSSED_CONN" ;

//PARAM NAMES


const m4pchar_t HOST =	"HOST" ;
const m4pchar_t BUFFER =	"BUFFER" ;
const m4pchar_t PORT	= "PORT" ;


#endif

