#ifndef __M4CACHETYPES_HPP
#define __M4CACHETYPES_HPP
//## begin module.epilog preserve=yes

//Tipos de caches existentes.
#define M4_CACHE_CMCR_CACHE_TYPE			0x1
#define M4_CACHE_CSCR_CACHE_TYPE			0x2
#define M4_CACHE_PRES_CACHE_TYPE			0x4
#define M4_CACHE_DATA_CACHE_TYPE			0x8
#define M4_CACHE_SESSION_STATE_CACHE_TYPE	0x10	//ClExecutorState (M4ExeForChannel)
#define M4_CACHE_XMLFILE_CACHE_TYPE			0x20
#define M4_CACHE_COMPILEDXML_CACHE_TYPE		0x40
#define M4_CACHE_SERVICEDLL_CACHE_TYPE		0x80
#define M4_CACHE_ASERVCONN_CACHE_TYPE		0x100
#define M4_CACHE_ISERVCONN_CACHE_TYPE		0x200
#define M4_CACHE_OBJDATA_CACHE_TYPE		    0x400
#define M4_CACHE_MAP_CACHE_TYPE				0x800
#define M4_CACHE_TABLE_CACHE_TYPE			0x1000
#define M4_CACHE_LITERALS_CACHE_TYPE		0x2000

#define M4_CACHE_NONE_CACHE_TYPE			0x0
#define M4_CACHE_ALL_MD_CACHE_TYPE			0xF
#define M4_CACHE_ALL_CACHE_TYPE				0xFFFF

//## end module.epilog
#endif // __M4CACHETYPES_HPP 
