#ifndef __M4COTYPES_HPP
#define __M4COTYPES_HPP
//## begin module.epilog preserve=yes

//Tipos de cacheobject existentes.
#define M4_CO_FACTORY_BASIC_CACHEABLE_OBJECT		0
#define M4_CO_FACTORY_CMCR_CONTAINER				1
#define M4_CO_FACTORY_CSCR_CONTAINER				2
#define M4_CO_FACTORY_PRESENTATION_CONTAINER		3
#define M4_CO_FACTORY_DATA_CONTAINER				10
#define M4_CO_FACTORY_SESSION_DATA_CONTAINER		11
#define M4_CO_FACTORY_XMLFILE_CONTAINER				12
#define M4_CO_FACTORY_COMPILEDXML_CONTAINER			13
#define M4_CO_FACTORY_SERVICEDLL_CONTAINER			14
#define M4_CO_FACTORY_ASERVCONN_CONTAINER			15
#define M4_CO_FACTORY_ISERVCONN_CONTAINER			16
#define M4_CO_FACTORY_OBJDATA_CONTAINER             17
#define M4_CO_FACTORY_MAP_CONTAINER					18


//## end module.epilog
#endif // __M4COTYPES_HPP 
