

#ifndef SNMP_OBJ_DEFINES_HPP
#define SNMP_OBJ_DEFINES_HPP


#define SNMP_SITE_OBJ_TYPE			"SITE"
#define SNMP_SERVER_OBJ_TYPE		"SERVER"
#define SNMP_CONFIGID_OBJ_TYPE		"SERVER_CONFIGURATION"
#define SNMP_SERVER_MEMORY_OBJ_TYPE	"SERVER_MEMORY"
#define SNMP_SYSTEM_CPU_OBJ_TYPE	"SYSTEM_CPU"
#define SNMP_SYSTEM_MEMORY_OBJ_TYPE	"SYSTEM_MEMORY"
/*
#define SNMP_SERVER_OBJ_TYPE	"SERVER"
#define SNMP_SERVER_OBJ_TYPE	"SERVER"
#define SNMP_SERVER_OBJ_TYPE	"SERVER"
#define SNMP_SERVER_OBJ_TYPE	"SERVER"
*/


#define SNMP_SITE_OBJ_TYPE_ID			0
#define SNMP_SERVER_OBJ_TYPE_ID			1
#define SNMP_CONFIGID_OBJ_TYPE_ID		2
#define SNMP_SERVER_MEMORY_OBJ_TYPE_ID	3
#define SNMP_SYSTEM_CPU_OBJ_TYPE_ID		4
#define SNMP_SYSTEM_MEMORY_OBJ_TYPE_ID	5


#define SNMP_START_CONFIG_COMMAND	0

#define SNMP_START_CONFIG_COMMAND_ID	0
#endif

